# Generated by Django 6.0.5 on 2026-05-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_seed_bike_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketype',
            name='slug',
            field=models.SlugField(choices=[('road', 'Road'), ('mountain', 'Mountain'), ('gravel', 'Gravel'), ('fixed', 'Fixed Gear')], unique=True),
        ),
    ]
