# Generated by Django 6.0.5 on 2026-05-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('bike_type', models.CharField(choices=[('road', 'Road'), ('mountain', 'Mountain'), ('gravel', 'Gravel'), ('fixed', 'Fixed'), ('any', 'Any')], default='any', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_grams', models.PositiveIntegerField(help_text='Weight in grams')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('affiliate_url', models.URLField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='category.category')),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
    ]
