# Generated by Django 6.0.5 on 2026-05-21 20:19

from django.db import migrations

BIKE_TYPES = [
    ("road", "Road"),
    ("mountain", "Mountain"),
    ("gravel", "Gravel"),
    ("fixed", "Fixed Gear"),
]


def seed_bike_types(apps, schema_editor):
    BikeType = apps.get_model("category", "BikeType")
    for slug, name in BIKE_TYPES:
        BikeType.objects.get_or_create(slug=slug, defaults={"name": name})


def unseed_bike_types(apps, schema_editor):
    BikeType = apps.get_model("category", "BikeType")
    BikeType.objects.filter(slug__in=[s for s, _ in BIKE_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_biketype_bottombracket_brake_cassette_crankset_fork_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_bike_types, reverse_code=unseed_bike_types),
    ]
