# Generated by Django 6.0.5 on 2026-05-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_seed_bike_type_component_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brake',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bike_types',
        ),
        migrations.RemoveField(
            model_name='component',
            name='category',
        ),
        migrations.RemoveField(
            model_name='handlebar',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='saddle',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='stem',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='wheel',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='rearderailleur',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='frontderailleur',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='fork',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='seatpost',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='crankset',
            name='component_ptr',
        ),
        migrations.DeleteModel(
            name='BottomBracket',
        ),
        migrations.DeleteModel(
            name='Brake',
        ),
        migrations.DeleteModel(
            name='Cassette',
        ),
        migrations.DeleteModel(
            name='Handlebar',
        ),
        migrations.DeleteModel(
            name='Saddle',
        ),
        migrations.DeleteModel(
            name='Stem',
        ),
        migrations.DeleteModel(
            name='Wheel',
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='RearDerailleur',
        ),
        migrations.DeleteModel(
            name='FrontDerailleur',
        ),
        migrations.DeleteModel(
            name='Fork',
        ),
        migrations.DeleteModel(
            name='Seatpost',
        ),
        migrations.DeleteModel(
            name='Tire',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Crankset',
        ),
    ]
