# Generated by Django 6.0.5 on 2026-05-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_brake_component_ptr_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biketypecomponentrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='biketypecomponentrule',
            name='bike_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='biketype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='slug',
            field=models.SlugField(choices=[('road', 'Road'), ('mountain', 'Mountain'), ('gravel', 'Gravel'), ('fixed', 'Fixed Gear')]),
        ),
        migrations.DeleteModel(
            name='BikeTypeComponentRule',
        ),
    ]
