# Generated by Django 6.0.5 on 2026-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_biketypecomponentrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketype',
            name='slug',
            field=models.SlugField(choices=[('fixed', 'Fixed Gear')]),
        ),
    ]
