# Generated by Django 6.0.5 on 2026-05-31 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('frame', 'Frame'), ('fork', 'Fork'), ('bottom_bracket', 'Bottom Bracket'), ('crankset', 'Crankset'), ('cassette', 'Cassette'), ('rear_derailleur', 'Rear Derailleur'), ('front_derailleur', 'Front Derailleur'), ('wheel', 'Wheel'), ('tire', 'Tire'), ('handlebar', 'Handlebar'), ('stem', 'Stem'), ('brake', 'Brake'), ('saddle', 'Saddle'), ('seatpost', 'Seatpost')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_grams', models.PositiveIntegerField(help_text='Weight in grams')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('affiliate_url', models.URLField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BottomBracket',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('shell_type', models.CharField(choices=[('threaded', 'Threaded (BSA)'), ('press_fit', 'Press Fit'), ('t47', 'T47'), ('bb30', 'BB30')], max_length=20)),
                ('spindle_interface', models.CharField(choices=[('square_taper', 'Square Taper'), ('isis', 'ISIS/Octalink'), ('24mm', '24mm (Shimano/SRAM)'), ('30mm', '30mm (BB30)'), ('dub', 'SRAM DUB')], max_length=20)),
                ('shell_width_mm', models.PositiveSmallIntegerField()),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Brake',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('brake_type', models.CharField(choices=[('rim_caliper', 'Rim Caliper'), ('rim_cantilever', 'Rim Cantilever'), ('disc_mechanical', 'Disc Mechanical'), ('disc_hydraulic', 'Disc Hydraulic')], max_length=20)),
                ('mount_type', models.CharField(blank=True, choices=[('flat_mount', 'Flat Mount'), ('post_mount', 'Post Mount'), ('is_mount', 'IS Mount')], max_length=20)),
                ('rotor_size_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear')], max_length=10)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('speeds', models.PositiveSmallIntegerField()),
                ('min_cog', models.PositiveSmallIntegerField()),
                ('max_cog', models.PositiveSmallIntegerField()),
                ('freehub_standard', models.CharField(choices=[('hg', 'Shimano HG'), ('xd', 'SRAM XD'), ('xdr', 'SRAM XDR'), ('micro_spline', 'Shimano Micro Spline')], max_length=20)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Crankset',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('spindle_interface', models.CharField(choices=[('square_taper', 'Square Taper'), ('isis', 'ISIS/Octalink'), ('24mm', '24mm (Shimano)'), ('30mm', '30mm (SRAM)'), ('dub', 'SRAM DUB')], max_length=20)),
                ('arm_length_mm', models.PositiveSmallIntegerField()),
                ('chainring_count', models.PositiveSmallIntegerField()),
                ('bcd', models.PositiveSmallIntegerField(blank=True, help_text='Bolt circle diameter in mm, null for direct mount', null=True)),
                ('speeds', models.PositiveSmallIntegerField(help_text='1 for single speed / fixed')),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(choices=[('carbon', 'Carbon'), ('aluminium', 'Aluminium'), ('steel', 'Steel')], max_length=20)),
                ('bb_shell', models.CharField(choices=[('threaded', 'Threaded (BSA)'), ('press_fit', 'Press Fit'), ('t47', 'T47'), ('bb30', 'BB30')], max_length=20)),
                ('head_tube_type', models.CharField(choices=[('stright', 'Stright'), ('tapered', 'Tapered')], max_length=20)),
                ('rear_axle_standard', models.CharField(choices=[('track_120', 'Track 120mm'), ('qr_130', 'Quick Release 130mm'), ('qr_135', 'Quick Release 135mm'), ('thru_142', 'Thru Axle 142mm'), ('thur_148', 'Thru Axle 148mm')], max_length=20)),
                ('max_tire_clearance_mm', models.PositiveSmallIntegerField()),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='FrontDerailleur',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('speeds', models.PositiveSmallIntegerField()),
                ('clamp_type', models.CharField(choices=[('braze_on', 'Braze-on'), ('28.6mm', '28.6mm Clamp'), ('31.8mm', '31.8mm Clamp'), ('direct_mount', 'Direct Mount')], max_length=20)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Handlebar',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('bar_type', models.CharField(choices=[('drop', 'Drop'), ('flat', 'Flat'), ('riser', 'Riser'), ('bullhorn', 'Bullhorn')], max_length=20)),
                ('width_mm', models.PositiveSmallIntegerField()),
                ('clamp_diameter_mm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('drop_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reach_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='RearDerailleur',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('speeds', models.PositiveSmallIntegerField()),
                ('max_cog_size', models.PositiveSmallIntegerField()),
                ('clutch', models.BooleanField(default=False)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Saddle',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('width_mm', models.PositiveSmallIntegerField()),
                ('rail_type', models.CharField(choices=[('round', 'Round'), ('oval', 'Oval')], max_length=10)),
                ('rail_material', models.CharField(choices=[('steel', 'Steel'), ('titanium', 'Titanium'), ('carbon', 'Carbon')], max_length=20)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Seatpost',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('diameter_mm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('length_mm', models.PositiveSmallIntegerField()),
                ('offset_mm', models.PositiveSmallIntegerField(default=0)),
                ('post_type', models.CharField(choices=[('standard', 'Standard'), ('dropper', 'Dropper')], default='standard', max_length=20)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('length_mm', models.PositiveSmallIntegerField()),
                ('bar_clamp_diameter_mm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('steerer_clamp_diameter_mm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('angle_degrees', models.SmallIntegerField()),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('wheel_size', models.CharField(choices=[('26', '26"'), ('27.5', '27.5"'), ('29', '29"'), ('700c', '700c'), ('650b', '650b')], max_length=10)),
                ('width_mm', models.PositiveSmallIntegerField()),
                ('tubeless_ready', models.BooleanField(default=False)),
                ('tread_type', models.CharField(choices=[('slick', 'Slick'), ('semi_slick', 'Semi-Slick'), ('knobby', 'Knobby')], max_length=20)),
            ],
            bases=('components.components',),
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('wheel_size', models.CharField(choices=[('26', '26"'), ('27.5', '27.5"'), ('29', '29"'), ('700c', '700c'), ('650b', '650b')], max_length=10)),
                ('position', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear')], max_length=10)),
                ('axle_standard', models.CharField(choices=[('qr_100', 'Quick Release Front (100mm)'), ('qr_135', 'Quick Release Rear (135mm)'), ('thru_100', 'Thru Axle Front (100mm)'), ('thru_110', 'Thru Axle Front Boost (110mm)'), ('thru_142', 'Thru Axle Rear (142mm)'), ('thru_148', 'Thru Axle Rear Boost (148mm)')], max_length=20)),
                ('max_tire_width_mm', models.PositiveSmallIntegerField()),
                ('tubeless_ready', models.BooleanField(default=False)),
            ],
            bases=('components.components',),
        ),
    ]
