# Generated by Django 6.0.5 on 2026-06-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_reseed_with_subclass_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='axle_standard',
            field=models.CharField(choices=[('track_120', 'Track 120mm'), ('qr_100', 'Quick Release Front (100mm)'), ('qr_130', 'Quick Release (130mm)'), ('qr_135', 'Quick Release (135mm)'), ('thru_100', 'Thru Axle Front (100mm)'), ('thru_110', 'Thru Axle Front Boost (110mm)'), ('thru_142', 'Thru Axle (142mm)'), ('thru_148', 'Thru Axle Boost (148mm)')], max_length=20),
        ),
    ]
