# Generated by Django 6.0.5 on 2026-06-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_alter_wheel_axle_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontderailleur',
            name='components_ptr',
        ),
        migrations.RemoveField(
            model_name='rearderailleur',
            name='components_ptr',
        ),
        migrations.RemoveField(
            model_name='brake',
            name='position',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='head_tube_type',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='material',
        ),
        migrations.AlterField(
            model_name='brake',
            name='brake_type',
            field=models.CharField(choices=[('rim_caliper', 'Rim Caliper'), ('rim_cantilever', 'Rim Cantilever')], max_length=20),
        ),
        migrations.AlterField(
            model_name='components',
            name='component_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('bottom_bracket', 'Bottom Bracket'), ('crankset', 'Crankset'), ('wheel', 'Wheel'), ('tire', 'Tire'), ('handlebar', 'Handlebar'), ('stem', 'Stem'), ('brake', 'Brake'), ('saddle', 'Saddle'), ('seatpost', 'Seatpost')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Cassette',
        ),
        migrations.DeleteModel(
            name='FrontDerailleur',
        ),
        migrations.DeleteModel(
            name='RearDerailleur',
        ),
    ]
