# Generated by Django 6.0.5 on 2026-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_sprocket_chain_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='hub_type',
            field=models.CharField(choices=[('threaded', 'Threaded'), ('spline', 'Spline')], default='threaded', max_length=10),
        ),
    ]
