# Generated by Django 6.0.5 on 2026-06-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_seed_wheel_hub_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackHub',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
            ],
            bases=('components.components',),
        ),
        migrations.RemoveField(
            model_name='components',
            name='affiliate_url',
        ),
        migrations.RemoveField(
            model_name='components',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='components',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='components',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crankset',
            name='bcd',
        ),
        migrations.RemoveField(
            model_name='crankset',
            name='chainring_count',
        ),
        migrations.RemoveField(
            model_name='crankset',
            name='speeds',
        ),
        migrations.AlterField(
            model_name='bottombracket',
            name='shell_type',
            field=models.CharField(choices=[('threaded_bsa', 'Threaded (BSA/English)'), ('threaded_ita', 'Threaded (Italian)'), ('t47', 'T47 Threaded'), ('pf86_92', 'Press Fit (BB86/BB92)'), ('pf30', 'PressFit 30'), ('bb30', 'BB30')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bottombracket',
            name='spindle_interface',
            field=models.CharField(choices=[('square_taper_iso', 'Square Taper ISO'), ('square_taper_jis', 'Square Taper JIS'), ('octalink', 'Shimano Octalink'), ('isis', 'ISIS Drive'), ('24mm', '24mm (Shimano Hollowtech II)'), ('gxp', 'SRAM GXP (24mm/22mm stepped)'), ('30mm', '30mm (BB30/386EVO)'), ('dub', 'SRAM DUB (28.99mm)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='components',
            name='component_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('bottom_bracket', 'Bottom Bracket'), ('crankset', 'Crankset'), ('chainring', 'Chainring'), ('sprocket', 'Sprocket'), ('chain', 'Chain'), ('wheel', 'Wheel'), ('track_hub', 'Track Hub'), ('tire', 'Tire'), ('handlebar', 'Handlebar'), ('stem', 'Stem'), ('brake', 'Brake'), ('saddle', 'Saddle'), ('seatpost', 'Seatpost'), ('pedals', 'Pedals')], max_length=30),
        ),
        migrations.AlterField(
            model_name='crankset',
            name='arm_length_mm',
            field=models.CharField(choices=[('160mm', '160mm'), ('165mm', '165mm'), ('170mm', '170mm')], max_length=5),
        ),
        migrations.AlterField(
            model_name='crankset',
            name='spindle_interface',
            field=models.CharField(choices=[('square_taper_iso', 'Square Taper ISO'), ('square_taper_jis', 'Square Taper JIS'), ('octalink', 'Shimano Octalink'), ('isis', 'ISIS Drive'), ('24mm', '24mm (Shimano Hollowtech II)'), ('gxp', 'SRAM GXP (24mm/22mm stepped)'), ('30mm', '30mm (BB30/386EVO)'), ('dub', 'SRAM DUB (28.99mm)')], max_length=20),
        ),
    ]
