# Generated by Django 6.0.5 on 2026-06-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_trackhub_remove_components_affiliate_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='components',
            index=models.Index(fields=['component_type', 'brand', 'name'], name='components__compone_264804_idx'),
        ),
    ]
