# Generated by Django 6.0.5 on 2026-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_components_components__compone_264804_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='import_url',
            field=models.URLField(blank=True),
        ),
    ]
