# Generated by Django 6.0.5 on 2026-07-04 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_components_import_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='import_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
