# Generated by Django 6.0.5 on 2026-07-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0018_componentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottombracket',
            old_name='shell_type',
            new_name='bb_type',
        ),
        migrations.RenameField(
            model_name='bottombracket',
            old_name='shell_width_mm',
            new_name='bb_width_mm',
        ),
        migrations.RemoveField(
            model_name='crankset',
            name='arm_length_mm',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='bb_shell',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='size',
        ),
        migrations.AddField(
            model_name='frame',
            name='bb_type',
            field=models.CharField(blank=True, choices=[('threaded_bsa', 'Threaded (BSA/English)'), ('threaded_ita', 'Threaded (Italian)'), ('t47', 'T47 Threaded'), ('pf86_92', 'Press Fit (BB86/BB92)'), ('pf30', 'PressFit 30'), ('bb30', 'BB30')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='bb_width_mm',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='fork_brake_drilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_brake_drilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frame',
            name='seat_tube',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CrankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('length_mm', models.CharField(choices=[('160mm', '160mm'), ('165mm', '165mm'), ('167.5mm', '167.5mm'), ('170mm', '170mm')], max_length=10)),
                ('chainring_teeth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crankset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.crankset')),
            ],
            options={
                'ordering': ['crankset', 'color', 'length_mm'],
            },
        ),
        migrations.CreateModel(
            name='FrameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='components.frame')),
            ],
            options={
                'ordering': ['frame', 'size'],
            },
        ),
    ]
