# Generated by Django 6.0.5 on 2026-07-26 22:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_rename_shell_type_bottombracket_bb_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottombracket',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list),
        ),
    ]
