# Generated by Django 6.0.5 on 2026-07-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_bottombracket_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crankoption',
            options={'ordering': ['crankset', 'color', 'chainring_teeth', 'length_mm']},
        ),
        migrations.RenameField(
            model_name='bottombracket',
            old_name='spindle_interface',
            new_name='spindle_interface_mm',
        ),
        migrations.RenameField(
            model_name='crankset',
            old_name='spindle_interface',
            new_name='spindle_interface_mm',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='rear_axle_standard',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='seat_tube',
        ),
        migrations.AddField(
            model_name='bottombracket',
            name='spindle_length_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crankset',
            name='spindle_length_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='fork_type',
            field=models.CharField(blank=True, choices=[('tapered', 'Tapered'), ('straight', 'Straight')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='seatpost_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='bottombracket',
            name='bb_type',
            field=models.CharField(choices=[('bsa', 'BSA'), ('ita', 'Italian'), ('t47', 'T47'), ('pf86_92', 'Press Fit (BB86/BB92)'), ('pf30', 'PressFit 30'), ('bb30', 'BB30')], max_length=20),
        ),
        migrations.AlterField(
            model_name='frame',
            name='bb_type',
            field=models.CharField(blank=True, choices=[('bsa', 'BSA'), ('ita', 'Italian'), ('t47', 'T47'), ('pf86_92', 'Press Fit (BB86/BB92)'), ('pf30', 'PressFit 30'), ('bb30', 'BB30')], max_length=20, null=True),
        ),
    ]
