# Generated by Django 6.0.5 on 2026-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0021_alter_crankoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottombracket',
            name='bb_type',
            field=models.CharField(blank=True, choices=[('bsa', 'BSA'), ('ita', 'Italian'), ('t47', 'T47'), ('pf86_92', 'Press Fit (BB86/BB92)'), ('pf30', 'PressFit 30'), ('bb30', 'BB30')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bottombracket',
            name='bb_width_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
