# Generated by Django 6.0.5 on 2026-07-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_alter_bottombracket_bb_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottombracket',
            name='bb_type',
        ),
        migrations.RemoveField(
            model_name='bottombracket',
            name='colors',
        ),
        migrations.CreateModel(
            name='BottomBracketOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_type', models.CharField(choices=[('bsa', 'BSA'), ('ita', 'Italian'), ('t47', 'T47'), ('pf86_92', 'Press Fit (BB86/BB92)'), ('pf30', 'PressFit 30'), ('bb30', 'BB30')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottom_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.bottombracket')),
            ],
            options={
                'ordering': ['bottom_bracket', 'color', 'bb_type'],
            },
        ),
    ]
