# Generated by Django 6.0.5 on 2026-07-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_remove_bottombracket_bb_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rim',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('wheel_size', models.CharField(choices=[('26', '26"'), ('27.5', '27.5"'), ('29', '29"'), ('700c', '700c'), ('650b', '650b')], max_length=10)),
                ('max_tire_width_mm', models.PositiveSmallIntegerField()),
                ('hole_count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('components.components', models.Model),
        ),
        migrations.CreateModel(
            name='WheelSet',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('wheel_size', models.CharField(choices=[('26', '26"'), ('27.5', '27.5"'), ('29', '29"'), ('700c', '700c'), ('650b', '650b')], max_length=10)),
                ('max_tire_width_mm', models.PositiveSmallIntegerField()),
                ('rim_name', models.CharField(blank=True, max_length=200)),
                ('hub_name', models.CharField(blank=True, max_length=200)),
                ('rear_hub_spacing', models.CharField(blank=True, choices=[('100mm', '100mm'), ('110mm', '110mm'), ('120mm', '120mm'), ('130mm', '130mm')], max_length=6)),
                ('cog_interface', models.CharField(blank=True, choices=[('fixed_single', 'Single-Sided Fixed'), ('flip_flop_fix_free', 'Flip-Flop (Fixed / Freewheel)'), ('flip_flop_fix_fix', 'Flip-Flop (Fixed / Fixed)'), ('splined', 'Splined Track (e.g., Miche / Shimano)')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('components.components', models.Model),
        ),
        migrations.AddField(
            model_name='trackhub',
            name='cog_interface',
            field=models.CharField(blank=True, choices=[('fixed_single', 'Single-Sided Fixed'), ('flip_flop_fix_free', 'Flip-Flop (Fixed / Freewheel)'), ('flip_flop_fix_fix', 'Flip-Flop (Fixed / Fixed)'), ('splined', 'Splined Track (e.g., Miche / Shimano)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trackhub',
            name='hole_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackhub',
            name='hub_spacing',
            field=models.CharField(blank=True, choices=[('100mm', '100mm'), ('110mm', '110mm'), ('120mm', '120mm'), ('130mm', '130mm')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='trackhub',
            name='position',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='trackhub',
            name='threading',
            field=models.CharField(blank=True, choices=[('iso_english', 'Standard English/ISO (1.37 x 24 TPI)'), ('njs_jis', 'NJS/JIS (Keirin standard)'), ('campagnolo', 'Campagnolo Threading'), ('french', 'Vintage French Threading')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='components',
            name='component_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('bottom_bracket', 'Bottom Bracket'), ('crankset', 'Crankset'), ('chainring', 'Chainring'), ('sprocket', 'Sprocket'), ('chain', 'Chain'), ('wheel', 'Wheel'), ('wheelset', 'Wheelset'), ('rim', 'Rim'), ('track_hub', 'Track Hub'), ('tire', 'Tire'), ('handlebar', 'Handlebar'), ('stem', 'Stem'), ('brake', 'Brake'), ('saddle', 'Saddle'), ('seatpost', 'Seatpost'), ('pedals', 'Pedals')], max_length=30),
        ),
    ]
