# Generated by Django 6.0.5 on 2026-07-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_rim_wheelset_trackhub_cog_interface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleWheel',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('wheel_size', models.CharField(choices=[('26', '26"'), ('27.5', '27.5"'), ('29', '29"'), ('700c', '700c'), ('650b', '650b')], max_length=10)),
                ('max_tire_width_mm', models.PositiveSmallIntegerField()),
                ('position', models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], default='', max_length=10)),
                ('hub_spacing', models.CharField(blank=True, choices=[('100mm', '100mm'), ('110mm', '110mm'), ('120mm', '120mm'), ('130mm', '130mm')], default='', max_length=6)),
                ('cog_interface', models.CharField(blank=True, choices=[('fixed_single', 'Single-Sided Fixed'), ('flip_flop_fix_free', 'Flip-Flop (Fixed / Freewheel)'), ('flip_flop_fix_fix', 'Flip-Flop (Fixed / Fixed)'), ('splined', 'Splined Track (e.g., Miche / Shimano)')], default='', max_length=20)),
                ('threading', models.CharField(blank=True, choices=[('iso_english', 'Standard English/ISO (1.37 x 24 TPI)'), ('njs_jis', 'NJS/JIS (Keirin standard)'), ('campagnolo', 'Campagnolo Threading'), ('french', 'Vintage French Threading')], default='', max_length=25)),
                ('hub_type', models.CharField(choices=[('threaded', 'Threaded'), ('spline', 'Spline')], default='threaded', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('components.components', models.Model),
        ),
        migrations.DeleteModel(
            name='Wheel',
        ),
    ]
