# Generated by Django 6.0.5 on 2026-07-30 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_singlewheel_delete_wheel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackhub',
            name='cog_interface',
        ),
        migrations.RemoveField(
            model_name='trackhub',
            name='hole_count',
        ),
        migrations.CreateModel(
            name='HubOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('hole_count', models.PositiveSmallIntegerField()),
                ('cog_interface', models.CharField(choices=[('fixed_single', 'Single-Sided Fixed'), ('flip_flop_fix_free', 'Flip-Flop (Fixed / Freewheel)'), ('flip_flop_fix_fix', 'Flip-Flop (Fixed / Fixed)'), ('splined', 'Splined Track (e.g., Miche / Shimano)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('track_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.trackhub')),
            ],
            options={
                'ordering': ['track_hub', 'color', 'hole_count', 'cog_interface'],
            },
        ),
    ]
