# Generated by Django 6.0.5 on 2026-07-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_remove_trackhub_cog_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huboption',
            name='cog_interface',
            field=models.CharField(blank=True, choices=[('fixed_single', 'Single-Sided Fixed'), ('flip_flop_fix_free', 'Flip-Flop (Fixed / Freewheel)'), ('flip_flop_fix_fix', 'Flip-Flop (Fixed / Fixed)'), ('splined', 'Splined Track (e.g., Miche / Shimano)')], default='', max_length=20),
        ),
    ]
