# Generated by Django 6.0.5 on 2026-07-31 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_alter_huboption_cog_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrankArm',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('spindle_interface_mm', models.CharField(choices=[('square_taper_iso', 'Square Taper ISO'), ('square_taper_jis', 'Square Taper JIS'), ('octalink', 'Shimano Octalink'), ('isis', 'ISIS Drive'), ('24mm', '24mm (Shimano Hollowtech II)'), ('gxp', 'SRAM GXP (24mm/22mm stepped)'), ('30mm', '30mm (BB30/386EVO)'), ('dub', 'SRAM DUB (28.99mm)')], max_length=20)),
                ('spindle_length_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            bases=('components.components',),
        ),
        migrations.AlterField(
            model_name='components',
            name='component_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('bottom_bracket', 'Bottom Bracket'), ('crankset', 'Crankset'), ('crank_arm', 'Crank Arm'), ('chainring', 'Chainring'), ('sprocket', 'Sprocket'), ('chain', 'Chain'), ('wheel', 'Wheel'), ('wheelset', 'Wheelset'), ('rim', 'Rim'), ('track_hub', 'Track Hub'), ('tire', 'Tire'), ('handlebar', 'Handlebar'), ('stem', 'Stem'), ('brake', 'Brake'), ('saddle', 'Saddle'), ('seatpost', 'Seatpost'), ('pedals', 'Pedals')], max_length=30),
        ),
        migrations.CreateModel(
            name='CrankArmOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('length_mm', models.CharField(choices=[('160mm', '160mm'), ('165mm', '165mm'), ('167.5mm', '167.5mm'), ('170mm', '170mm')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crank_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.crankarm')),
            ],
            options={
                'ordering': ['crank_arm', 'color', 'length_mm'],
            },
        ),
    ]
