# Generated by Django 6.0.5 on 2026-07-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0028_crankarm_alter_components_component_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crankarmoption',
            name='length_mm',
            field=models.CharField(choices=[('160mm', '160mm'), ('165mm', '165mm'), ('167.5mm', '167.5mm'), ('170mm', '170mm'), ('172.5mm', '172.5mm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='crankoption',
            name='length_mm',
            field=models.CharField(choices=[('160mm', '160mm'), ('165mm', '165mm'), ('167.5mm', '167.5mm'), ('170mm', '170mm'), ('172.5mm', '172.5mm')], max_length=10),
        ),
    ]
