# Generated by Django 6.0.5 on 2026-07-31 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_alter_crankarmoption_length_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chainring',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('chainring_teeth', models.PositiveSmallIntegerField()),
                ('colour', models.CharField(blank=True, max_length=15, null=True)),
                ('bcd', models.CharField(blank=True, choices=[('144', '144mm BCD'), ('130', '130mm BCD'), ('110', '110mm BCD'), ('135', '135mm BCD'), ('104', '104mm BCD')], max_length=4, null=True)),
            ],
            bases=('components.components',),
        ),
        migrations.AddField(
            model_name='crankarm',
            name='bcd',
            field=models.CharField(blank=True, choices=[('144', '144mm BCD'), ('130', '130mm BCD'), ('110', '110mm BCD'), ('135', '135mm BCD'), ('104', '104mm BCD')], max_length=4, null=True),
        ),
    ]
