# Generated by Django 6.0.5 on 2026-07-31 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0030_chainring_crankarm_bcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainring',
            name='chainring_teeth',
        ),
        migrations.RemoveField(
            model_name='chainring',
            name='colour',
        ),
        migrations.CreateModel(
            name='ChainringOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('chainring_teeth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chainring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.chainring')),
            ],
            options={
                'ordering': ['chainring', 'chainring_teeth', 'color'],
            },
        ),
    ]
