# Generated by Django 6.0.5 on 2026-07-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0031_remove_chainring_chainring_teeth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottombracketoption',
            name='image_colour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chainringoption',
            name='image_colour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='crankarmoption',
            name='image_colour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='crankoption',
            name='image_colour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='huboption',
            name='image_colour_url',
            field=models.URLField(blank=True),
        ),
    ]
