# Generated by Django 6.0.5 on 2026-08-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0032_bottombracketoption_image_colour_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedals',
            fields=[
                ('components_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.components')),
                ('colour', models.CharField(max_length=30)),
            ],
            bases=('components.components',),
        ),
        migrations.RemoveField(
            model_name='handlebar',
            name='width_mm',
        ),
        migrations.RemoveField(
            model_name='rim',
            name='hole_count',
        ),
        migrations.RemoveField(
            model_name='saddle',
            name='rail_material',
        ),
        migrations.RemoveField(
            model_name='saddle',
            name='rail_type',
        ),
        migrations.RemoveField(
            model_name='saddle',
            name='width_mm',
        ),
        migrations.RemoveField(
            model_name='seatpost',
            name='diameter_mm',
        ),
        migrations.RemoveField(
            model_name='seatpost',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='seatpost',
            name='offset_mm',
        ),
        migrations.RemoveField(
            model_name='seatpost',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='stem',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='tread_type',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='tubeless_ready',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='width_mm',
        ),
        migrations.AlterField(
            model_name='bottombracketoption',
            name='image_colour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainringoption',
            name='image_colour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crankarmoption',
            name='image_colour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crankoption',
            name='image_colour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='max_tire_clearance_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frameoption',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.frame'),
        ),
        migrations.AlterField(
            model_name='huboption',
            name='hole_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='huboption',
            name='image_colour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rim',
            name='max_tire_width_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlewheel',
            name='max_tire_width_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprocket',
            name='sprocket_teeth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wheelset',
            name='max_tire_width_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HandlebarOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handlebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.handlebar')),
            ],
        ),
        migrations.CreateModel(
            name='RimOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('hole_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_colour_url', models.URLField(blank=True, null=True)),
                ('rim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.rim')),
            ],
        ),
        migrations.CreateModel(
            name='SaddleOptiosn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.saddle')),
            ],
        ),
        migrations.CreateModel(
            name='SeatPostOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_mm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('length_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seatpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.seatpost')),
            ],
        ),
        migrations.CreateModel(
            name='SprocketOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sprocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.sprocket')),
            ],
        ),
        migrations.CreateModel(
            name='StemOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('image_colour_url', models.URLField(blank=True, null=True)),
                ('stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.stem')),
            ],
        ),
        migrations.CreateModel(
            name='TireOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.tire')),
            ],
        ),
    ]
