# Generated by Django 6.0.5 on 2026-06-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
