# Generated by Django 6.0.5 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_build_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='name',
            field=models.CharField(default='New Build', max_length=40),
        ),
    ]
