# Generated by Django 6.0.5 on 2026-06-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
