# Generated by Django 6.0.5 on 2026-06-25 01:55

import secrets

import apps.builds.models
from django.db import migrations, models


def backfill_share_tokens(apps, schema_editor):
    Build = apps.get_model('builds', 'Build')
    for build in Build.objects.filter(share_token='').only('id'):
        token = secrets.token_urlsafe(9)[:12]
        while Build.objects.filter(share_token=token).exists():
            token = secrets.token_urlsafe(9)[:12]
        build.share_token = token
        build.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_build_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='share_token',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.RunPython(backfill_share_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='build',
            name='share_token',
            field=models.CharField(db_index=True, default=apps.builds.models.generate_share_token, editable=False, max_length=12, unique=True),
        ),
    ]
