# Generated by Django 6.0.5 on 2026-06-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
