# Generated by Django 6.0.5 on 2026-06-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_build_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-created_at']},
        ),
    ]
