# Generated by Django 6.0.5 on 2026-06-27 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_alter_build_options'),
        ('category', '0009_alter_biketype_slug_add_road_gravel_mountain'),
        ('components', '0014_components_components__compone_264804_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['status'], name='builds_buil_status_b90502_idx'),
        ),
    ]
