# Generated by Django 6.0.5 on 2026-08-02 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_build_builds_buil_status_b90502_idx'),
        ('category', '0009_alter_biketype_slug_add_road_gravel_mountain'),
        ('components', '0032_bottombracketoption_image_colour_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_build_idempotency_key'),
        ),
    ]
